CoinTradePros.Web/Controllers/PackageController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using CoinTradePros.BusinessObjects;
using CoinTradePros.Web.Helpers;
using CoinTradePros.Web.Models;
using Tiraggo.Interfaces;

namespace CoinTradePros.Web.Controllers
{
    public partial class PackageController : Controller
    {
        // GET: Trade
        [Authorize(Roles = "ProTrader, Admin")]
        public virtual ActionResult Index()
        {
            ViewBag.Title = "Sales Packages";
            ICollection<PackageModel> packages = ModelHelper.FillPackagesForUser(IdentityHelper.GetCurrentUserId(User));
            return View(packages);
        }

        // GET: Trade/Details/5
        [Authorize(Roles = "Trader,ProTrader, Admin")]
        public virtual ActionResult Details(Guid packageid)
        {
            ViewBag.Title = "Package Details";
            PackageModel model = ModelHelper.FillPackage(packageid);
            return View(model);
        }

        // GET: Trade/Create
        [Authorize(Roles = "Trader,ProTrader, Admin")]
        public virtual ActionResult Create(Guid? proTraderProfileId)
        {
            PackageModel model = new PackageModel();
            if (proTraderProfileId.HasValue && proTraderProfileId != Guid.Empty)
            {
                model.ProxyProTraderProfileId = proTraderProfileId;
                model.ProTraderProfileId = proTraderProfileId;
            }
            else
            {
                model.ProTraderProfileId = IdentityHelper.GetCurrentUserProTraderId(User);
            }
            model.FeatureItems = ModelHelper.GetBaseFeatureSelectItems(model.ProTraderProfileId.Value);
            return View(model);
        }

        // POST: Trade/Create
        [HttpPost]
        [Authorize(Roles = "Trader,ProTrader")]
        public virtual ActionResult Create(PackageModel model)
        {
            try
            {
                bool isProxyMode = model.ProxyProTraderProfileId.HasValue &&
                                   model.ProxyProTraderProfileId != Guid.Empty;
                ViewBag.Title = "New Sales Package";
                if (!model.ProxyProTraderProfileId.HasValue && !model.ProxyProTraderProfileId.HasValue)
                {
                    model.ProTraderProfileId = IdentityHelper.GetCurrentUserProTraderId(User);
                }
                if (ModelState.IsValid)
                {
                    Package package = new Package();
                    package.Id = Guid.NewGuid();
                    package.AnnualPrice = model.AnnualPrice;
                    package.Description = model.Description;
                    package.LifetimePrice = model.LifetimePrice;
                    package.MonthlyPrice = model.MonthlyPrice;
                    package.Title = model.Title;
                    if (isProxyMode)
                    {
                        package.ProTraderProfileId = model.ProxyProTraderProfileId;
                    }
                    else
                    {
                        package.ProTraderProfileId = model.ProTraderProfileId;
                    }
                    ProTraderProfile profile = new ProTraderProfile();
                    profile.LoadByPrimaryKey(model.ProTraderProfileId ?? Guid.Empty);

                    Guid traderId = profile.TraderId ?? Guid.Empty;
                    UploadHelper uploadHelper = new UploadHelper(traderId, Server.MapPath("~/"));


                    package.IconPath = uploadHelper.GetFinalItemRelativePath(model.PackageIcon);
                    package.Save(tgSqlAccessType.DynamicSQL);

                    string[] selectedFeatures = { "" };
                    if (Request.Form["FeatureData"] != null)
                    {
                        selectedFeatures = Request.Form["FeatureData"].Split(',');
                    }
                    foreach (string f in selectedFeatures)
                    {
                        Guid fid;
                        if (Guid.TryParse(f, out fid))
                        {
                            PackageFeature pf = new PackageFeature();

                            pf.PackageId = package.Id;
                            pf.FeatureId = fid;
                            pf.Save(tgSqlAccessType.DynamicSQL);
                        }
                    }

                    if (model.IsProxyMode())
                    {
                        return RedirectToAction("Index", "SalesPage",
                            new { proTraderProfileId = model.ProxyProTraderProfileId });
                    }
                    return RedirectToAction("Index", "SalesPage");
                }
                if (model.IsProxyMode())
                {
                    model.ProTraderProfileId = model.ProxyProTraderProfileId;
                }
                else
                {
                    model.ProTraderProfileId = IdentityHelper.GetCurrentUserProTraderId(User);
                }
                model.FeatureItems = ModelHelper.GetBaseFeatureSelectItems(model.ProTraderProfileId ?? Guid.Empty);
                return View(model);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Exception", ex.ToString());
                FillDefaults(model);
                return View(model);
            }
        }

        // GET: Trade/Edit/5
        [Authorize(Roles = "Trader,ProTrader, Admin")]
        public virtual ActionResult Edit(Guid? packageid, Guid? proTraderProfileId)
        {
            PackageModel model;
            if (packageid.HasValue)
            {
                model = ModelHelper.FillPackage(packageid.Value);
            }
            else
            {
                model = new PackageModel();
            }
            if (proTraderProfileId.HasValue && proTraderProfileId != Guid.Empty)
            {
                model.ProxyProTraderProfileId = proTraderProfileId;
                model.ProTraderProfileId = proTraderProfileId;
            }
            else
            {
                model.ProTraderProfileId = IdentityHelper.GetCurrentUserProTraderId(User);
            }
            return View(model);
        }

        // POST: Trade/Edit/5
        [HttpPost]
        [Authorize(Roles = "Trader,ProTrader, Admin")]
        public virtual ActionResult Edit(PackageModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Package package = new Package();
                    if (model.PackageId.HasValue && package.LoadByPrimaryKey(model.PackageId.Value))
                    {
                        if (model.IsProxyMode())
                        {
                            package.ProTraderProfileId = model.ProxyProTraderProfileId;
                        }
                        else
                        {
                            package.ProTraderProfileId = model.ProTraderProfileId;
                        }

                        package.AnnualPrice = model.AnnualPrice;
                        package.Description = model.Description;
                        package.IconPath = model.IconPath;
                        package.Id = model.PackageId;
                        package.MonthlyPrice = model.MonthlyPrice;
                        package.AnnualPrice = model.AnnualPrice;
                        package.Title = model.Title;
                        package.LifetimePrice = model.LifetimePrice;
                        ProTraderProfile profile = new ProTraderProfile();
                        profile.LoadByPrimaryKey(package.ProTraderProfileId ?? Guid.Empty);

                        Guid traderId = profile.TraderId ?? Guid.Empty;
                        UploadHelper uploadHelper = new UploadHelper(traderId, Server.MapPath("~/"));
                        package.IconPath = uploadHelper.GetFinalItemRelativePath(model.PackageIcon);
                        package.Save(tgSqlAccessType.DynamicSQL);
                        if (Request.Form["FeatureData"] != null)
                        {
                            string[] selectedFeatures = Request.Form["FeatureData"].Split(',');
                            package.SaveFeatures(selectedFeatures);
                        }
                        if (model.IsProxyMode())
                        {
                            return RedirectToAction("Index", "SalesPage", new { proTraderProfileId = model.ProxyProTraderProfileId });
                        }
                        return RedirectToAction("Index", "SalesPage");
                    }
                    ModelState.AddModelError("PackageId", $"The package id {model.PackageId ?? Guid.Empty} was not found.");
                }
                else
                {
                    ModelState.AddModelError("General", "Please double check your package information for any errors.");
                }
                // repopulate the dropdowns and return to sender
                FillDefaults(model);
                return View(model);
            }
            catch (Exception ex)
            {
                // repopulate the dropdowns and return to sender
                ModelState.AddModelError("Unknown Error", ex);
                FillDefaults(model);
                return View(model);
            }
        }

        // GET: Trade/Delete/5
        [Authorize(Roles = "Trader,ProTrader")]
        public virtual ActionResult Delete(Guid? packageid, Guid? proTraderProfileId)
        {
            Package package = new Package();
            if (packageid.HasValue && package.LoadByPrimaryKey(packageid.Value))
            {
                // The PackageFeature items related to this package are deleted via cascade.
                package.MarkAsDeleted();
                package.Save(tgSqlAccessType.DynamicSQL);
            }
            if (proTraderProfileId.HasValue && proTraderProfileId != Guid.Empty)
            {

CoinTradePros.Web/Views/Package/Create.cshtml
@model CoinTradePros.Web.Models.PackageModel
@{
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";

}
<section id="main-content" class=" ">
<section class="wrapper main-wrapper row" style=''>
    @using (Html.BeginForm(null, null, FormMethod.Post, new {enctype = "multipart/form-data"}))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @if (Model.IsProxyMode())
            {
                <h2 class="text-danger">You are editing this account on behalf of another user</h2>
            }
            @Html.ValidationSummary(false, string.Empty, new {@class = "text-danger"})
            <div class="form-group row">
                @Html.LabelFor(model => model.Title, new {@class = "col-form-label col-md-3"})
                <div class="col-md-9">
                    @Html.TextBoxFor(model => Model.Title, new {@class = "form-control"})
                    @Html.ValidationMessageFor(model => model.Title, "", new {@class = "text-danger"})
                </div>
            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.Description, new {@class = "col-form-label col-md-3"})
                <div class="col-md-9">
                    @Html.TextAreaFor(model => model.Description, new {@class = "form-control"})
                    @Html.ValidationMessageFor(model => model.Description, "", new {@class = "text-danger"})
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.MonthlyPrice, htmlAttributes: new {@class = "col-form-label col-md-3"})
                <div class="col-md-9">
                    @Html.TextBoxFor(model => model.MonthlyPrice, new {@class = "form-control"})
                    @Html.ValidationMessageFor(model => model.MonthlyPrice, "", new {@class = "text-danger"})
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.AnnualPrice, new {@class = "col-form-label col-md-3"})
                <div class="col-md-9">
                    @Html.TextBoxFor(model => model.AnnualPrice, new {@class = "form-control"})
                    @Html.ValidationMessageFor(model => model.AnnualPrice, "", new {@class = "text-danger"})
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.LifetimePrice, new {@class = "col-form-label col-md-3"})
                <div class="col-md-9">
                    @Html.TextBoxFor(model => model.LifetimePrice, new {@class = "form-control"})
                    @Html.ValidationMessageFor(model => model.LifetimePrice, "", new {@class = "text-danger"})
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.PackageIcon, new {@class = "col-form-label col-md-3"})
                <div class="col-md-9">
                    @Html.TextBoxFor(model => model.PackageIcon, new {@class = "form-control", type = "file"})
                    @Html.ValidationMessageFor(model => model.PackageIcon, "", new {@class = "text-danger"})
                </div>
            </div>

            <div class="card" style="margin-bottom: 2em;">
                <div class="card-header">
                    Package Features
                </div>
                <div class="card-block">
                    <h4 class="card-title">
                        Select the Features to Include in This Package
                    </h4>
                    <br/>

                    @if (Model.FeatureItems.Count > 0)
                    {
                        foreach (var feature in Model.FeatureItems)
                        {
                            string id = $"pk_{feature.Value}";
                            <label for="@id" class="custom-control custom-checkbox">
                                <input type="checkbox" id="@id" value="@feature.Value" name="FeatureData" class="custom-control-input"/>
                                <span class="custom-control-indicator"></span>
                                <span class="custom-control-description">@feature.Text</span>
                            </label>
                            <br/>
                        }
                    }
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3"></div>
                <div class="col-md-9">
                    <button type="submit" class="btn btn-lg btn-success">
                        <span class="fa fa-plus"></span>
                        Add
                    </button>
                    @if (Model.IsProxyMode())
                    {
                        <button class="btn btn-lg btn-secondary" type="button" onclick="window.location = '@Url.Action("Index", "Package", new {proTraderProfileId = Model.ProxyProTraderProfileId})'">
                            <span class="fa fa-ban"></span>
                            Cancel
                        </button>
                    }
                    else
                    {
                        <button class="btn btn-lg btn-secondary" type="button" onclick="window.location = '@Url.Action("Index", "Package")'">
                            <span class="fa fa-ban"></span>
                            Cancel
                        </button>
                    }
                </div>
            </div>
            @if (Model.IsProxyMode())
            {
                @Html.HiddenFor(model => model.ProxyProTraderProfileId)
            }
            @Html.HiddenFor(model => model.ProTraderProfileId)
        </div>
    }
    </section>
</section>

CoinTradePros.Web/Views/Package/Details.cshtml
@model CoinTradePros.Web.Models.PackageModel
@{
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";

}
<section id="main-content" style="margin-top: 80px;" class=" ">
    <div>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.PackageId)
            </dt>
            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PackageId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MonthlyPrice)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.AnnualPrice)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LifetimePrice)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.IconPath)
            </dt>
            <dt>
                @Html.DisplayNameFor(model => model.ProTraderProfileId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ProTraderProfileId)
            </dd>
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", "Trade", new { traderid = Model.PackageId }) |
        @Html.ActionLink("Delete", "Delete", "Trade", new { traderid = Model.PackageId }) |
        @Html.ActionLink("Back to List", "Index", "Trade")
    </p>
    </section>

CoinTradePros.Web/Views/Package/Edit.cshtml
@model CoinTradePros.Web.Models.PackageModel
@{
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";

}
<section id="main-content" class=" ">
<section class="wrapper main-wrapper row" style=''>
    <div class="modal fade" id="DeleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="deleteModalLabel">Delete Question</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Cancel">
                        <span class="fa fa-close"></span>
                    </button>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete this package?
                </div>
                <div class="modal-actions">
                    @if (Model.IsProxyMode())
                    {
                        <a href="@Url.Action("Delete", "Package", new {packageid = Model.PackageId, proTraderProfileId = Model.ProxyProTraderProfileId})" class="btn modal-action btn-danger">
                            <span class="fa fa-trash-o"></span>
                            Delete
                        </a>
                    }
                    else
                    {
                        <a href="@Url.Action("Delete", "Package", new {tradeid = Model.PackageId})" class="btn modal-action btn-danger">
                            <span class="fa fa-trash-o"></span>
                            Delete
                        </a>
                    }
                    <button class="btn modal-action btn-secondary" type="button" aria-label="close" data-dismiss="modal">
                        <span class="fa fa-close"></span>
                        Close
                    </button>
                </div>
            </div>
        </div>
    </div>


    @using (Html.BeginForm(null, null, FormMethod.Post, new {enctype = "multipart/form-data"}))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @if (Model.IsProxyMode())
            {
                <h2 class="text-danger">You are editing this account on behalf of another user</h2>
            }
            @Html.ValidationSummary(false, string.Empty, new {@class = "text-danger"})
            <div class="form-group row">
                @Html.LabelFor(model => model.Title, new {@class = "col-form-label col-md-3"})
                <div class="col-md-9">
                    @Html.TextBoxFor(model => model.Title,new {@class = "form-control"})
                    @Html.ValidationMessageFor(model => model.Title, String.Empty, new {@class = "text-danger"})
                </div>
            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.Description, new {@class = "col-form-label col-md-3"})
                <div class="col-md-9">
                    @Html.TextAreaFor(model => model.Description, new {@class = "form-control"})
                    @Html.ValidationMessageFor(model => model.Description, "", new {@class = "text-danger"})
                </div>
            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.MonthlyPrice, new {@class = "col-form-label col-md-3"})
                <div class="col-md-9">
                    @Html.TextBoxFor(model => model.MonthlyPrice, new{@class = "form-control"})
                    @Html.ValidationMessageFor(model => model.MonthlyPrice, "", new {@class = "text-danger"})
                </div>
            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.AnnualPrice, new {@class = "col-form-label col-md-3"})
                <div class="col-md-9">
                    @Html.TextBoxFor(model => model.AnnualPrice, new {@class = "form-control"})
                    @Html.ValidationMessageFor(model => model.AnnualPrice, "", new {@class = "text-danger"})
                </div>
            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.LifetimePrice, new {@class = "col-form-label col-md-3"})
                <div class="col-md-9">
                    @Html.TextBoxFor(model => model.LifetimePrice, new {@class = "form-control"})
                    @Html.ValidationMessageFor(model => model.LifetimePrice, "", new {@class = "text-danger"})
                </div>
            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.PackageIcon, new {@class = "col-form-label col-md-3"})
                <div class="col-md-9">
                    @Html.TextBoxFor(model => model.PackageIcon, new {@class = "form-control", type = "file"})
                    @Html.ValidationMessageFor(model => model.PackageIcon, "", new {@class = "text-danger"})
                </div>
            </div>
            @if (Model.IsProxyMode())
            {
                @Html.HiddenFor(model => model.ProxyProTraderProfileId)
            }

            <div class="card" style="margin-bottom: 2em;">
                <h4 class="card-header">
                    Package Features
                </h4>
                <div class="card-block">
                    <h5 class="card-title">
                        Select the Features to Include in This Package
                    </h5>
                    <br/>
                    @if (Model.FeatureItems.Count > 0)
                    {
                        foreach (var feature in Model.FeatureItems)
                        {
                            string id = $"pk_{feature.Value}";
                            <label for="@id" class="custom-control custom-checkbox">
                                <input type="checkbox" id="@id" value="@feature.Value" checked="@feature.Selected" name="FeatureData" class="custom-control-input"/>
                                <span class="custom-control-indicator"></span>
                                <span class="custom-control-description">@feature.Text</span>
                            </label>
                            <br/>
                        }
                    }
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-3"></div>
                <div class="col-md-9">
                    <button type="submit" class="btn btn-primary">
                        <span class="fa fa-check"></span>
                        Update
                    </button>
                    @if (Model.IsProxyMode())
                    {
                        <button class="btn btn-secondary" type="button" onclick="window.location = '@Url.Action("Index", "SalesPage", new {proTraderProfileId = Model.ProxyProTraderProfileId})'">
                            <span class="fa fa-ban"></span>
                            Cancel
                        </button>
                    }
                    else
                    {
                        <button class="btn btn-secondary" type="button" onclick="window.location = '@Url.Action("Index", "SalesPage")'">
                            <span class="fa fa-ban"></span>
                            Cancel
                        </button>

                    }
                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#DeleteModal">
                        <span class="fa fa-trash-o"></span>
                        Delete
                    </button>
                </div>
            </div>
            @if (Model.IsProxyMode())
            {
                @Html.HiddenFor(model => model.ProxyProTraderProfileId)
            }
            @Html.HiddenFor(model => model.ProTraderProfileId)
            @Html.HiddenFor(model => model.PackageId)
        </div>
    }
    </section>
</section>

CoinTradePros.Web/Views/Package/Index.cshtml
@model IEnumerable<CoinTradePros.Web.Models.PackageModel>
@{
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";

}
<section id="main-content" style="margin-top: 80px;" class=" ">
<table class="table table-condensed table-striped table-responsive table-hover">
    <thead class="thead-default">
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Monthly Price</th>
        <th>Annual Price</th>
        <th>Lifetime Price</th>
        <th>Current Subscribers</th>
        <th width="33%">Features</th>
        <th colspan="2" align="right">
      
            <a href="@Url.Action("Create")" class="btn btn-sm btn-primary">Add a Package</a>
        </th>
    </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.Title
            </td>
            <td>
                @item.Description
            </td>
            <td>
                @($"{item.MonthlyPrice:C}")
            </td>
            <td>
                @($"{item.AnnualPrice:C}")
            </td>
            <td>
                @($"{item.LifetimePrice:C}")
            </td>
            <td>
                @item.CurrentSubscriberCount
            </td>
            <td>
                <ul>
                    @{
                        foreach (SelectListItem f in item.FeatureItems)
                        {
                            if (f.Selected)
                            {
                                <li id="@f.Value" value="@f.Value">@f.Text</li>
                            }
                        }
                    }
                </ul>
            </td>
            <td>
                @if (item.IsProxyMode())
                {
                    <a href="@Url.Action("Edit", new {packageid = item.PackageId, proTraderProfileId = item.ProTraderProfileId})" class="btn btn-xs btn-secondary">Edit</a>
                }
                else
                {
                    <a href="@Url.Action("Edit", new {packageid = item.PackageId})" class="btn btn-xs btn-secondary">Edit</a>
                }
            </td>
            <td>
                @if (item.IsProxyMode())
                {
                    <a href="@Url.Action("Delete", new {packageid = item.PackageId, proTraderProfileId = item.ProTraderProfileId})" class="btn btn-xs btn-danger">Delete</a>
                }
                else
                {
                    <a href="@Url.Action("Delete", new {packageid = item.PackageId})" class="btn btn-xs btn-danger">Delete</a>
                }
            </td>
        </tr>
    }
</table>
    </section>